//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFCNMaintenance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInquiryReferralStatu
    {
        public Nullable<int> CareGiverID { get; set; }
        public Nullable<bool> InitialInquiry1 { get; set; }
        public Nullable<System.DateTime> DateInitialInquiry { get; set; }
        public Nullable<int> StaffInitialInquiry { get; set; }
        public Nullable<bool> DidntPass2 { get; set; }
        public Nullable<System.DateTime> DateDidntPass { get; set; }
        public Nullable<int> StaffDidntPass { get; set; }
        public Nullable<bool> LookingJob3 { get; set; }
        public Nullable<System.DateTime> DateLookingJob { get; set; }
        public Nullable<int> StaffLookingJob { get; set; }
        public Nullable<bool> OutOfState4 { get; set; }
        public Nullable<System.DateTime> DateOutOfStat { get; set; }
        public Nullable<int> StaffOutOfStat { get; set; }
        public Nullable<bool> Inactive5 { get; set; }
        public Nullable<System.DateTime> DateInactive { get; set; }
        public Nullable<int> StaffInactive { get; set; }
        public Nullable<bool> Active6 { get; set; }
        public Nullable<System.DateTime> DateActive { get; set; }
        public Nullable<int> StaffActive { get; set; }
        public Nullable<bool> AppReceived7 { get; set; }
        public Nullable<System.DateTime> DateAppReceived { get; set; }
        public Nullable<int> StaffAppReceived { get; set; }
        public Nullable<bool> AppProgram8 { get; set; }
        public Nullable<System.DateTime> DateAppProgram { get; set; }
        public Nullable<int> StaffAppProgram { get; set; }
        public Nullable<bool> AppReferrdProg9 { get; set; }
        public Nullable<System.DateTime> DateAppReferredProg { get; set; }
        public Nullable<int> StaffAppReferredProg { get; set; }
        public Nullable<bool> HomeCert10 { get; set; }
        public Nullable<System.DateTime> DateHomeCert1 { get; set; }
        public Nullable<int> StaffHomeCert { get; set; }
        public Nullable<bool> HomeClosed11 { get; set; }
        public Nullable<System.DateTime> DateHomeClosed { get; set; }
        public Nullable<int> StaffHomeClosed { get; set; }
        public Nullable<bool> AppOnHold12 { get; set; }
        public Nullable<System.DateTime> DateAppOnHold { get; set; }
        public Nullable<int> StaffAppOnHold { get; set; }
        public Nullable<bool> AppReturned13 { get; set; }
        public Nullable<System.DateTime> DateAppReturned { get; set; }
        public Nullable<int> StaffAppReturned { get; set; }
        public Nullable<bool> AppReferredtoAnother14 { get; set; }
        public Nullable<System.DateTime> DateAppReferredtoAnother { get; set; }
        public Nullable<int> StaffAppReferredtoAnother { get; set; }
        public Nullable<bool> AppRejectedProg15 { get; set; }
        public Nullable<System.DateTime> DateAppRejectedFFCN { get; set; }
        public Nullable<int> StaffAppRejectedFFCN { get; set; }
        public Nullable<bool> AppRejectedFFCN16 { get; set; }
        public Nullable<System.DateTime> DateAppRejectedProg { get; set; }
        public Nullable<int> StaffAppRejectedProg { get; set; }
        public Nullable<int> ReasonAppProgram { get; set; }
        public string ReasonAppReferredProg { get; set; }
        public Nullable<int> ReasonHomeCert { get; set; }
        public string ReasonHomeClosed { get; set; }
        public string ReasonAppOnHold { get; set; }
        public string ReasonAppReturned { get; set; }
        public Nullable<int> ReasonAppReferredAnother { get; set; }
        public string ReasonAppRejectedProg { get; set; }
        public int IDIRS { get; set; }
        public string ReasonAppRejectedFFCN { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public string ReasonInactive { get; set; }
    
        public virtual tlkpProgram tlkpProgram { get; set; }
        public virtual tlkpProgram tlkpProgram1 { get; set; }
        public virtual tlkpProgram tlkpProgram2 { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual tblUser tblUser2 { get; set; }
        public virtual tblUser tblUser3 { get; set; }
        public virtual tblUser tblUser4 { get; set; }
        public virtual tblUser tblUser5 { get; set; }
        public virtual tblUser tblUser6 { get; set; }
        public virtual tblUser tblUser7 { get; set; }
        public virtual tblUser tblUser8 { get; set; }
        public virtual tblUser tblUser9 { get; set; }
        public virtual tblUser tblUser10 { get; set; }
        public virtual tblUser tblUser11 { get; set; }
        public virtual tblUser tblUser12 { get; set; }
        public virtual tblUser tblUser13 { get; set; }
        public virtual tblUser tblUser14 { get; set; }
        public virtual tblUser tblUser15 { get; set; }
        public virtual tblPrimaryCaregiverdata tblPrimaryCaregiverdata { get; set; }
    }
}
