//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFCNMaintenance.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    
    public partial class tblPhone
    {
        public int id { get; set; }
        public Nullable<int> CareGiverID { get; set; }
        public string Phone { get; set; }
        public Nullable<int> PhoneType { get; set; }
        public Nullable<bool> Active { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual tblPrimaryCaregiverdata tblPrimaryCaregiverdata { get; set; }
        public virtual tlkpPhoneType tlkpPhoneType { get; set; }

        public virtual SelectList PhoneTypeSelectList { get; set; }
    }
}
