//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFCNMaintenance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public tblUser()
        {
            this.tblCommunications = new HashSet<tblCommunication>();
            this.tblInquiryReferralStatus = new HashSet<tblInquiryReferralStatu>();
            this.tblInquiryReferralStatus1 = new HashSet<tblInquiryReferralStatu>();
            this.tblInquiryReferralStatus2 = new HashSet<tblInquiryReferralStatu>();
            this.tblInquiryReferralStatus3 = new HashSet<tblInquiryReferralStatu>();
            this.tblInquiryReferralStatus4 = new HashSet<tblInquiryReferralStatu>();
            this.tblInquiryReferralStatus5 = new HashSet<tblInquiryReferralStatu>();
            this.tblInquiryReferralStatus6 = new HashSet<tblInquiryReferralStatu>();
            this.tblInquiryReferralStatus7 = new HashSet<tblInquiryReferralStatu>();
            this.tblInquiryReferralStatus8 = new HashSet<tblInquiryReferralStatu>();
            this.tblInquiryReferralStatus9 = new HashSet<tblInquiryReferralStatu>();
            this.tblInquiryReferralStatus10 = new HashSet<tblInquiryReferralStatu>();
            this.tblInquiryReferralStatus11 = new HashSet<tblInquiryReferralStatu>();
            this.tblInquiryReferralStatus12 = new HashSet<tblInquiryReferralStatu>();
            this.tblInquiryReferralStatus13 = new HashSet<tblInquiryReferralStatu>();
            this.tblInquiryReferralStatus14 = new HashSet<tblInquiryReferralStatu>();
            this.tblInquiryReferralStatus15 = new HashSet<tblInquiryReferralStatu>();
            this.tblTrainingHistoryMains = new HashSet<tblTrainingHistoryMain>();
            this.tblTrainingHistoryMains1 = new HashSet<tblTrainingHistoryMain>();
            this.tblTrainingHistoryMains2 = new HashSet<tblTrainingHistoryMain>();
            this.tblTrainingHistoryMains3 = new HashSet<tblTrainingHistoryMain>();
            this.tblTrainingHistoryMains4 = new HashSet<tblTrainingHistoryMain>();
            this.tblTrainingHistoryMains5 = new HashSet<tblTrainingHistoryMain>();
            this.tblTrainingHistoryMains6 = new HashSet<tblTrainingHistoryMain>();
            this.tblTrainingHistoryMains7 = new HashSet<tblTrainingHistoryMain>();
            this.tblTrainingHistoryMains8 = new HashSet<tblTrainingHistoryMain>();
            this.tblTrainingHistoryMains9 = new HashSet<tblTrainingHistoryMain>();
        }
    
        public int UserId { get; set; }
        public string First { get; set; }
        public string Last { get; set; }
        public Nullable<int> Agency { get; set; }
        public Nullable<int> UserGroup { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Active { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual ICollection<tblCommunication> tblCommunications { get; set; }
        public virtual ICollection<tblInquiryReferralStatu> tblInquiryReferralStatus { get; set; }
        public virtual ICollection<tblInquiryReferralStatu> tblInquiryReferralStatus1 { get; set; }
        public virtual ICollection<tblInquiryReferralStatu> tblInquiryReferralStatus2 { get; set; }
        public virtual ICollection<tblInquiryReferralStatu> tblInquiryReferralStatus3 { get; set; }
        public virtual ICollection<tblInquiryReferralStatu> tblInquiryReferralStatus4 { get; set; }
        public virtual ICollection<tblInquiryReferralStatu> tblInquiryReferralStatus5 { get; set; }
        public virtual ICollection<tblInquiryReferralStatu> tblInquiryReferralStatus6 { get; set; }
        public virtual ICollection<tblInquiryReferralStatu> tblInquiryReferralStatus7 { get; set; }
        public virtual ICollection<tblInquiryReferralStatu> tblInquiryReferralStatus8 { get; set; }
        public virtual ICollection<tblInquiryReferralStatu> tblInquiryReferralStatus9 { get; set; }
        public virtual ICollection<tblInquiryReferralStatu> tblInquiryReferralStatus10 { get; set; }
        public virtual ICollection<tblInquiryReferralStatu> tblInquiryReferralStatus11 { get; set; }
        public virtual ICollection<tblInquiryReferralStatu> tblInquiryReferralStatus12 { get; set; }
        public virtual ICollection<tblInquiryReferralStatu> tblInquiryReferralStatus13 { get; set; }
        public virtual ICollection<tblInquiryReferralStatu> tblInquiryReferralStatus14 { get; set; }
        public virtual ICollection<tblInquiryReferralStatu> tblInquiryReferralStatus15 { get; set; }
        public virtual ICollection<tblTrainingHistoryMain> tblTrainingHistoryMains { get; set; }
        public virtual ICollection<tblTrainingHistoryMain> tblTrainingHistoryMains1 { get; set; }
        public virtual ICollection<tblTrainingHistoryMain> tblTrainingHistoryMains2 { get; set; }
        public virtual ICollection<tblTrainingHistoryMain> tblTrainingHistoryMains3 { get; set; }
        public virtual ICollection<tblTrainingHistoryMain> tblTrainingHistoryMains4 { get; set; }
        public virtual ICollection<tblTrainingHistoryMain> tblTrainingHistoryMains5 { get; set; }
        public virtual ICollection<tblTrainingHistoryMain> tblTrainingHistoryMains6 { get; set; }
        public virtual ICollection<tblTrainingHistoryMain> tblTrainingHistoryMains7 { get; set; }
        public virtual ICollection<tblTrainingHistoryMain> tblTrainingHistoryMains8 { get; set; }
        public virtual ICollection<tblTrainingHistoryMain> tblTrainingHistoryMains9 { get; set; }
        public virtual tlkpAgency tlkpAgency { get; set; }
        public virtual tlkpUserGroup tlkpUserGroup { get; set; }
    }
}
