//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFCNMaintenance.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    
    public partial class tblTrainingHistoryMain
    {
        public int IDTR { get; set; }
        public Nullable<int> CareGiverID { get; set; }
        public Nullable<bool> Orientationmtg { get; set; }
        public Nullable<System.DateTime> DateOrient { get; set; }
        public Nullable<int> StaffOrient { get; set; }
        public Nullable<bool> RSVPd { get; set; }
        public Nullable<int> StaffIntro { get; set; }
        public Nullable<bool> IntroFoster { get; set; }
        public Nullable<int> StaffAttendedIntro { get; set; }
        public Nullable<bool> RSVPpreservice { get; set; }
        public Nullable<int> StaffPreserviceRSVP { get; set; }
        public Nullable<bool> AttendPreservice1 { get; set; }
        public Nullable<int> StaffAttendedPreservice1 { get; set; }
        public Nullable<bool> AttendPreservice2 { get; set; }
        public Nullable<int> StaffAttendedPreservice2 { get; set; }
        public Nullable<bool> OnHold { get; set; }
        public Nullable<bool> PreFinished8 { get; set; }
        public Nullable<System.DateTime> DatePreService { get; set; }
        public Nullable<int> StaffPreserviceComp { get; set; }
        public Nullable<int> OngoingTraining9 { get; set; }
        public Nullable<System.DateTime> DateOngoing { get; set; }
        public Nullable<int> StaffOngoing { get; set; }
        public Nullable<bool> OnetoOneOrientation { get; set; }
        public Nullable<System.DateTime> DateOneOnOne { get; set; }
        public Nullable<int> StaffOneOnOne { get; set; }
        public Nullable<bool> AttendedPrebefore2009 { get; set; }
        public Nullable<int> StaffPreservicePrior { get; set; }
        public Nullable<int> TrainDateIntro { get; set; }
        public Nullable<int> TrainDateAttendedIntro { get; set; }
        public Nullable<int> TrainDatePreserviceRSVP { get; set; }
        public Nullable<int> TrainDateAttendedPreservice1 { get; set; }
        public Nullable<int> TrainDateAttendedPreservice2 { get; set; }
        public Nullable<int> TrainDatePreserviceComp { get; set; }
        public Nullable<int> TrainDatePreservice2009 { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual tblPrimaryCaregiverdata tblPrimaryCaregiverdata { get; set; }
        public virtual tlkpOngoingTraining tlkpOngoingTraining { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual tblUser tblUser2 { get; set; }
        public virtual tblUser tblUser3 { get; set; }
        public virtual tblUser tblUser4 { get; set; }
        public virtual tblUser tblUser5 { get; set; }
        public virtual tblUser tblUser6 { get; set; }
        public virtual tblUser tblUser7 { get; set; }
        public virtual tblUser tblUser8 { get; set; }
        public virtual tblUser tblUser9 { get; set; }
        public virtual tlkpTrainPreserviceComp tlkpTrainPreserviceComp { get; set; }
        public virtual tlkpTrainPreservice2009 tlkpTrainPreservice2009 { get; set; }
        public virtual tlkpTrainPreservice2 tlkpTrainPreservice2 { get; set; }
        public virtual tlkpTrainPreserviceRSVP tlkpTrainPreserviceRSVP { get; set; }
        public virtual tlkpTrainPreservice1 tlkpTrainPreservice1 { get; set; }
        public virtual tlkpTrainIntroRSVP tlkpTrainIntroRSVP { get; set; }
        public virtual tlkpTrainAttendIntro tlkpTrainAttendIntro { get; set; }

        public virtual SelectList UserSelectList1 { get; set; }
        public virtual SelectList UserSelectList2 { get; set; }
        public virtual SelectList UserSelectList3 { get; set; }
        public virtual SelectList UserSelectList4 { get; set; }
        public virtual SelectList UserSelectList5 { get; set; }
        public virtual SelectList UserSelectList6 { get; set; }
        public virtual SelectList UserSelectList7 { get; set; }
        public virtual SelectList UserSelectList8 { get; set; }
        public virtual SelectList UserSelectList9 { get; set; }
        public virtual SelectList UserSelectList10 { get; set; }

        public virtual SelectList TrainIntroRSVP { get; set; }
        public virtual SelectList TrainAttendedIntro { get; set; }
        public virtual SelectList TrainPreserviceRSVP { get; set; }
        public virtual SelectList TrainAttendPreservice1 { get; set; }
        public virtual SelectList TrainAttendPreservice2 { get; set; }
        public virtual SelectList TrainPreserviceComp { get; set; }
        public virtual SelectList TrainPreservice2009 { get; set; }
        public virtual SelectList OngoingTraingingList { get; set; }
    }
}
